#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Scripts.cshtml"
    using Inspire.Common.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_Scripts.cshtml"
    using Inspire.Utilities.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Scripts.cshtml")]
    public partial class _Views_Shared__Scripts_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Scripts_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Scripts.cshtml"
  
    var controller = ViewContext.Controller;
    var controllerName = controller.GetControllerName();
    var area = CustomHelpers.GetControllerArea(ViewContext.Controller.GetType());

    var jsFile = new List<string>
     {
         "~/Scripts/Controllers/" + controllerName + ".js",
         "~/Scripts/Controllers/" + controllerName + "/" + controllerName + ".js"
     };

    if (area.IsNotNullOrEmpty())
    {
        jsFile.Add($"~/Areas/{area}/Scripts/Controllers/{controllerName}.js");
        jsFile.Add(string.Format("~/Areas/{0}/Scripts/Controllers/{1}/{1}.js", area, controllerName));
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 21 "..\..\Views\Shared\_Scripts.cshtml"
Write(Html.DynamicBundle(jsFile.ToArray()));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
