#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 1 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Shared\SearchForm.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 3 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 4 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\SearchForm.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 8 "..\..\Views\Shared\SearchForm.cshtml"
    using Inspire.Common.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\SearchForm.cshtml"
    using Inspire.Core.Infrastructure.Attribute;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\SearchForm.cshtml"
    using Inspire.Utilities.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SearchForm.cshtml")]
    public partial class _Views_Shared_SearchForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 123 "..\..\Views\Shared\SearchForm.cshtml"
public System.Web.WebPages.HelperResult GenerateSearchFields(object model, string controllerName)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 124 "..\..\Views\Shared\SearchForm.cshtml"
 
    var propsList = model.GetType().GetProperties() as IEnumerable<PropertyInfo>;
    foreach (var propertyInfo in propsList)
    {
        var displayAttribute = propertyInfo.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault() as DisplayAttribute;
        var queryOptionsAttribute = propertyInfo.GetCustomAttributes(typeof(QueryOptionsAttribute), false).FirstOrDefault() as QueryOptionsAttribute;

        var editorTemplateName = queryOptionsAttribute != null
            ? queryOptionsAttribute.Type == QueryOptionsAttribute.VisualType.Custom
                ? queryOptionsAttribute.EditorName
                : queryOptionsAttribute.Type != QueryOptionsAttribute.VisualType.None
                    ? string.Format("Query{0}", queryOptionsAttribute.Type)
                    : null
            : null;

        IEnumerable collection = null;
        if (editorTemplateName != null)
        {
            var dataSourceProperty = model.GetType().GetProperty(string.Format("{0}DataSource", propertyInfo.Name));
            if (dataSourceProperty != null)
            {
                collection = dataSourceProperty.GetValue(model) as IEnumerable;
            }
        }

        if (queryOptionsAttribute?.Type == QueryOptionsAttribute.VisualType.Hidden)
        {
            

#line default
#line hidden

#line 151 "..\..\Views\Shared\SearchForm.cshtml"
WriteTo(__razor_helper_writer, Html.Hidden(propertyInfo.Name));


#line default
#line hidden

#line 151 "..\..\Views\Shared\SearchForm.cshtml"
                                           
        }
        else if (displayAttribute != null)
        {
            if (queryOptionsAttribute?.CascadeFromField != null && queryOptionsAttribute?.ActionName != null)
            {
                ViewData["CascadeFromField"] = queryOptionsAttribute.CascadeFromField;
                ViewData["ActionName"] = queryOptionsAttribute.ActionName;
                ViewData["ControllerName"] = queryOptionsAttribute.ControllerName ?? controllerName;
            }

            if (queryOptionsAttribute?.ActionName != null && queryOptionsAttribute?.ControllerName != null)
            {
                ViewData["ActionName"] = queryOptionsAttribute.ActionName;
                ViewData["ControllerName"] = queryOptionsAttribute.ControllerName ?? controllerName;
            }

            if (User != null || queryOptionsAttribute != null && !queryOptionsAttribute.IsOnlyForSignedUsers)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 7545), Tuple.Create("\"", 7599)
, Tuple.Create(Tuple.Create("", 7553), Tuple.Create("form-input", 7553), true)

#line 170 "..\..\Views\Shared\SearchForm.cshtml"
, Tuple.Create(Tuple.Create(" ", 7563), Tuple.Create<System.Object, System.Int32>( queryOptionsAttribute?.CssClass

#line default
#line hidden
, 7564), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                    ");


#line 171 "..\..\Views\Shared\SearchForm.cshtml"
WriteTo(__razor_helper_writer, Html.Label(propertyInfo.Name));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "                    ");


#line 172 "..\..\Views\Shared\SearchForm.cshtml"
WriteTo(__razor_helper_writer, Html.Editor(
                        propertyInfo.Name,
                        editorTemplateName,
                        collection != null
                            ? new { Collection = collection, htmlAttributes = new { @class = "" } }
                            : new { htmlAttributes = new { @class = "" } } as object));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n                </div>\r\n");


#line 179 "..\..\Views\Shared\SearchForm.cshtml"
            }
            else
            {
                

#line default
#line hidden

#line 182 "..\..\Views\Shared\SearchForm.cshtml"
WriteTo(__razor_helper_writer, Html.Hidden(propertyInfo.Name));


#line default
#line hidden

#line 182 "..\..\Views\Shared\SearchForm.cshtml"
                                               
            }
        }
    }


#line default
#line hidden
});

#line 186 "..\..\Views\Shared\SearchForm.cshtml"
}
#line default
#line hidden

        public _Views_Shared_SearchForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 11 "..\..\Views\Shared\SearchForm.cshtml"
  
    var layout = ViewBag.Layout as string;
    if (layout.IsNotNullOrEmpty())
    {
        Layout = layout;
    }

    var controller = ViewContext.Controller;
    var controllerName = controller.GetControllerName();
    var area = CustomHelpers.GetControllerArea(ViewContext.Controller.GetType());

    var resultsDivId = Guid.NewGuid().ToString();

    var propsList = Model.GetType().GetProperties() as IEnumerable<PropertyInfo>;

    var searchQueryId = ViewBag.SearchQueryId as string ?? Guid.NewGuid().ToString();
    var searchButtonText = ViewBag.SearchButtonText as string;
    var isRequestAjax = ViewBag.IsAjaxRequest is bool && (bool)ViewBag.IsAjaxRequest;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"center\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Shared\SearchForm.cshtml"
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\SearchForm.cshtml"
     if (propsList.IsNotNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"searchbar\"");

WriteLiteral(">\r\n");

            
            #line 34 "..\..\Views\Shared\SearchForm.cshtml"
            
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\SearchForm.cshtml"
             if (!isRequestAjax)
            {
                using (Html.BeginForm("Search",
                                       controllerName,
                                       new { Area = area, searchQueryId },
                                       FormMethod.Get,
                                       new { @class = "search" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Shared\SearchForm.cshtml"
               Write(Html.Hidden("searchQueryId", searchQueryId));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Shared\SearchForm.cshtml"
                                                                ;

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"relative\"");

WriteLiteral(">\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1631), Tuple.Create("\"", 1658)
            
            #line 44 "..\..\Views\Shared\SearchForm.cshtml"
, Tuple.Create(Tuple.Create("", 1639), Tuple.Create<System.Object, System.Int32>(ViewBag.TableClass
            
            #line default
            #line hidden
, 1639), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 45 "..\..\Views\Shared\SearchForm.cshtml"
                       Write(GenerateSearchFields(Model, controllerName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"form-input tenth\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Shared\SearchForm.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\SearchForm.cshtml"
                                  
                                    var disableSearchButton = ViewBag.DisableSearchButton is bool && (bool)ViewBag.DisableSearchButton;
                                    if (!disableSearchButton)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <label");

WriteLiteral(" class=\"\"");

WriteLiteral(">&nbsp;</label>\r\n");

WriteLiteral("                                        <button");

WriteLiteral(" class=\"bttn secondary\"");

WriteLiteral(" type=\"submit\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2227), Tuple.Create("\"", 2252)
            
            #line 52 "..\..\Views\Shared\SearchForm.cshtml"
            , Tuple.Create(Tuple.Create("", 2235), Tuple.Create<System.Object, System.Int32>(searchButtonText
            
            #line default
            #line hidden
, 2235), false)
);

WriteLiteral(">");

            
            #line 52 "..\..\Views\Shared\SearchForm.cshtml"
                                                                                                          Write(searchButtonText);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 53 "..\..\Views\Shared\SearchForm.cshtml"
                                    }
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Views\Shared\SearchForm.cshtml"
                       Write(Html.DynamicAction("AdditionalSearchButtons", ViewContext.Controller.GetType()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 59 "..\..\Views\Shared\SearchForm.cshtml"
                }
            }
            else
            {
                using (Ajax.BeginForm(
                     "Search",
                     controllerName,
                     new { Area = area, searchQueryId },
                     new AjaxOptions
                     {
                         InsertionMode = InsertionMode.Replace,
                         HttpMethod = "GET",
                         UpdateTargetId = resultsDivId,
                         OnBegin = "kendo.ui.progress($('body'), true);",
                         OnComplete = "kendo.ui.progress($('body'), false);"
                     }, new { @class = "search" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"relative\"");

WriteLiteral(">\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3324), Tuple.Create("\"", 3351)
            
            #line 77 "..\..\Views\Shared\SearchForm.cshtml"
, Tuple.Create(Tuple.Create("", 3332), Tuple.Create<System.Object, System.Int32>(ViewBag.TableClass
            
            #line default
            #line hidden
, 3332), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 78 "..\..\Views\Shared\SearchForm.cshtml"
                       Write(GenerateSearchFields(Model, controllerName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"form-input tenth\"");

WriteLiteral(">\r\n");

            
            #line 80 "..\..\Views\Shared\SearchForm.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Shared\SearchForm.cshtml"
                                  
                                    var disableSearchButton = ViewBag.DisableSearchButton is bool && (bool)ViewBag.DisableSearchButton;
                                    if (!disableSearchButton)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <label");

WriteLiteral(" class=\"\"");

WriteLiteral(">&nbsp;</label>\r\n");

WriteLiteral("                                        <button");

WriteLiteral(" class=\"bttn secondary\"");

WriteLiteral(" type=\"submit\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3920), Tuple.Create("\"", 3945)
            
            #line 85 "..\..\Views\Shared\SearchForm.cshtml"
            , Tuple.Create(Tuple.Create("", 3928), Tuple.Create<System.Object, System.Int32>(searchButtonText
            
            #line default
            #line hidden
, 3928), false)
);

WriteLiteral(">");

            
            #line 85 "..\..\Views\Shared\SearchForm.cshtml"
                                                                                                          Write(searchButtonText);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 86 "..\..\Views\Shared\SearchForm.cshtml"
                                    }
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 89 "..\..\Views\Shared\SearchForm.cshtml"
                       Write(Html.DynamicAction("AdditionalSearchButtons", ViewContext.Controller.GetType()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 92 "..\..\Views\Shared\SearchForm.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 96 "..\..\Views\Shared\SearchForm.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 4322), Tuple.Create("\"", 4340)
            
            #line 97 "..\..\Views\Shared\SearchForm.cshtml"
, Tuple.Create(Tuple.Create("", 4327), Tuple.Create<System.Object, System.Int32>(resultsDivId
            
            #line default
            #line hidden
, 4327), false)
);

WriteLiteral(">\r\n");

            
            #line 98 "..\..\Views\Shared\SearchForm.cshtml"
        
            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Shared\SearchForm.cshtml"
          
            var isSearch = ViewBag.Search is bool && (bool)ViewBag.Search;
            var isAutoSearch = ViewBag.AutoSearch is bool && (bool)ViewBag.AutoSearch;
            if (isSearch || isAutoSearch)
            {
                var routeValueDictionary = Model != null ? new RouteValueDictionary(Model) : new RouteValueDictionary();
                routeValueDictionary.Add("searchQueryId", searchQueryId);
                Html.RenderDynamicAction(isRequestAjax ? "Search" : "SearchNoAjax", controller.GetType(), routeValueDictionary);
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("Breadcrumbs", () => {

WriteLiteral("\r\n");

            
            #line 112 "..\..\Views\Shared\SearchForm.cshtml"
    
            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Shared\SearchForm.cshtml"
      
        Html.RenderDynamicAction("Breadcrumbs", controller.GetType());
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

            
            #line 118 "..\..\Views\Shared\SearchForm.cshtml"
    
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\Shared\SearchForm.cshtml"
      
        Html.RenderDynamicAction("Scripts", controller.GetType());
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
